#!/usr/bin/env bash
# Test neo-tree H and y keys to see what's happening

echo "=== Testing Neo-tree H/y Issue ==="
echo ""
echo "1. Start nvim with your config:"
echo "   nvim"
echo ""
echo "2. Open neo-tree:"
echo "   Press <leader>e (space+e)"
echo ""
echo "3. Check what H is mapped to:"
echo "   In neo-tree, press '?' to see mappings"
echo "   Look for 'H' mapping"
echo ""
echo "4. Check what y is mapped to:"
echo "   Look for 'y' mapping in the help"
echo ""
echo "5. Test H:"
echo "   Press H in neo-tree"
echo "   Does it toggle hidden files?"
echo "   Does nvim exit with 'kill'?"
echo ""
echo "6. Test y:"
echo "   Select a file, press y"
echo "   Does it copy?"
echo "   Does nvim exit with 'kill'?"
echo ""
echo "7. Check nvim messages:"
echo "   After pressing H or y, check :messages"
echo "   Look for any error messages"
echo ""
echo "8. Check nvim log:"
echo "   :lua vim.cmd('messages')"
echo "   Or check ~/.local/state/nvim/lsp.log if LSP errors"
